/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Persis.ArchivoLectura;
import dominio.Pregunta;
import dominio.Sistema;
import java.util.ArrayList;

/**
 *
 * @author seba
 */
public class CargaDatosVentanaAuxiliar extends javax.swing.JFrame {
    Sistema sistema;
    /**
     * Creates new form CargaDatosVentanaAuxiliar
     */
    public CargaDatosVentanaAuxiliar(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPath = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        labelPath.setText("Path");
        getContentPane().add(labelPath);
        labelPath.setBounds(28, 12, 360, 15);

        jButton1.setText("Abrir navegador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 50, 250, 25);

        jButton2.setText("Mostrar path");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 100, 250, 25);

        jButton3.setText("Crear desde txt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 240, 150, 25);

        jButton4.setText("Cargar datoos a txt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 240, 130, 25);

        jButton5.setText("Carga facil de datos de prueba");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(63, 170, 290, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscarDocumento b = new BuscarDocumento(sistema);
        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        labelPath.setText(sistema.getPath());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArchivoLectura arch = new ArchivoLectura(sistema.getPath());
        int contador = 1;
        ArrayList<String> listaCargados = new ArrayList<>();
        while (arch.hayMasLineas()) {
            listaCargados.add(arch.linea());
        }
        arch.cerrar();
        boolean sePuedeAgregar = false;
        for (int i = 0; i < listaCargados.size(); i += 3) {
            System.out.println(listaCargados.get(i));
            System.out.println(listaCargados.get(i+1));
            System.out.println(listaCargados.get(i+2));
            for (int j = 0; j < sistema.getListaTemas().size(); j++) {
                if (listaCargados.get(i+1)!= "" && listaCargados.get(i+2)!="") {
                    if (sistema.getListaTemas().get(j).getNombre() == listaCargados.get(i).toString() && i / 3 == 0) {
                        System.out.println("entro");
                        Pregunta p = new Pregunta(listaCargados.get(i + 1).toString(), listaCargados.get(i + 2).toString(),
                            sistema.getListaTemas().get(j).getNombre(), sistema.getListaTemas().get(j).getDescripcion());
                    sistema.getListaPreguntas().add(p);
                    System.out.println(p.toString());
                }
                }
                
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CargaDatosPrueba c = new CargaDatosPrueba(sistema);
        c.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel labelPath;
    // End of variables declaration//GEN-END:variables
}
