/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Persis.ArchivoLectura;
import dominio.Pregunta;
import dominio.Sistema;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author seba
 */
public class CargaDatosVentanaAuxiliar extends javax.swing.JFrame {

    Sistema sistema;

    /**
     * Creates new form CargaDatosVentanaAuxiliar
     */
    public CargaDatosVentanaAuxiliar(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPath = new javax.swing.JLabel();
        abrirNavegador = new javax.swing.JButton();
        mostrarRuta = new javax.swing.JButton();
        cargaDatos = new javax.swing.JButton();
        guardarDatos = new javax.swing.JButton();
        cargaPrueba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        labelPath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPath.setText("Path");
        getContentPane().add(labelPath);
        labelPath.setBounds(10, 10, 380, 15);

        abrirNavegador.setText("Abrir navegador");
        abrirNavegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirNavegadorActionPerformed(evt);
            }
        });
        getContentPane().add(abrirNavegador);
        abrirNavegador.setBounds(70, 40, 250, 25);

        mostrarRuta.setText("Mostrar ruta seleccionada");
        mostrarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRutaActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarRuta);
        mostrarRuta.setBounds(70, 70, 250, 25);

        cargaDatos.setText("Cargar datos desde txt");
        cargaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaDatosActionPerformed(evt);
            }
        });
        getContentPane().add(cargaDatos);
        cargaDatos.setBounds(30, 170, 150, 25);

        guardarDatos.setText("Guardar datos a txt");
        guardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(guardarDatos);
        guardarDatos.setBounds(220, 170, 170, 25);

        cargaPrueba.setText("Carga facil de datos de prueba");
        cargaPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaPruebaActionPerformed(evt);
            }
        });
        getContentPane().add(cargaPrueba);
        cargaPrueba.setBounds(60, 250, 290, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirNavegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirNavegadorActionPerformed
        BuscarDocumento b = new BuscarDocumento(sistema);
        b.setVisible(true);
    }//GEN-LAST:event_abrirNavegadorActionPerformed

    private void mostrarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRutaActionPerformed
        labelPath.setText(sistema.getPath());
    }//GEN-LAST:event_mostrarRutaActionPerformed

    private void cargaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaDatosActionPerformed
        ArchivoLectura arch = new ArchivoLectura(sistema.getPath());
        ArrayList<String> listaCargados = new ArrayList<>();
        while (arch.hayMasLineas()) {
            listaCargados.add(arch.linea());
        }
        arch.cerrar();
        boolean sePuedeAgregar = false;
        for (int i = 0; i < listaCargados.size(); i += 3) {
            if (listaCargados.get(i) == "" || listaCargados.get(i + 1) == "" || listaCargados.get(i + 2) == "") {
                JOptionPane.showMessageDialog(null, "Hay espacios en blanco, no se pudo agregar la pregunta", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                for (int j = 0; j < sistema.getListaTemas().size(); j++) {
                    if (listaCargados.get(i + 1) != "" && listaCargados.get(i + 2) != "") {
                        if (sistema.getListaTemas().get(j).getNombre().equals(listaCargados.get(i).toUpperCase())) {
                            Pregunta p = new Pregunta(listaCargados.get(i + 1).toString(), listaCargados.get(i + 2).toString(),
                                    sistema.getListaTemas().get(j).getNombre(), sistema.getListaTemas().get(j).getDescripcion());
                            sistema.getListaPreguntas().add(p);
                            sistema.getListaTemas().get(j).setCantidadPreguntas(sistema.getListaTemas().get(j).getCantidadPreguntas() + 1);
                            System.out.println(p.toString());
                        }
                    }

                }

            }
        }
    }//GEN-LAST:event_cargaDatosActionPerformed

    private void guardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDatosActionPerformed

    }//GEN-LAST:event_guardarDatosActionPerformed

    private void cargaPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaPruebaActionPerformed
        CargaDatosPrueba c = new CargaDatosPrueba(sistema);
        c.setVisible(true);
    }//GEN-LAST:event_cargaPruebaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirNavegador;
    private javax.swing.JButton cargaDatos;
    private javax.swing.JButton cargaPrueba;
    private javax.swing.JButton guardarDatos;
    private javax.swing.JLabel labelPath;
    private javax.swing.JButton mostrarRuta;
    // End of variables declaration//GEN-END:variables
}
